"""
Django settings for school_server project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
from decouple import config
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1', 
    '.onrender.com',
    '*.vercel.app'
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'school_app',
    'corsheaders',
    
]
AUTH_USER_MODEL = 'school_app.User'
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware
    #'school_app.middleware.ip_whitelists.IPWhitelistMiddleware',  # Add this
]
# 'whitenoise.middleware.WhiteNoiseMiddleware', 
# Admin customization
ADMIN_SITE_HEADER = 'ElimuHub SYSTEM ADMINISTRATION'
ADMIN_SITE_TITLE = 'ElimuHub Admin Portal'
ADMIN_INDEX_TITLE = 'System Administration Dashboard'


ROOT_URLCONF = 'school_server.urls'

# CORS SETTINGS (CRITICAL for React-Django communication)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React development server
    "http://127.0.0.1:5173",
    "https://elimu-hub-one.vercel.app",
    
    
    # Add your production frontend URL here
]
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com', 'https://elimu-hub-one.vercel.app', 'http://localhost:5173', 'http://127.0.0.1:5173']



# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS settings


# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = config('DJANGO_ENV', default='development') == 'production'
SESSION_COOKIE_SAMESITE = 'Lax'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    }
}

# Security settings for production

if config('DJANGO_ENV', default='development') == 'production':
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Add these at the top of your settings.py


# Replace the DATABASES section of your settings.py with this
# tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
#     }
# }
DATABASES = {
    'default': dj_database_url.config(default=config("DATABASE_URL"))
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi' 

USE_I18N = True

USE_TZ = True

JAZZMIN_SETTINGS = {
    "site_title": "ElimuHub Admin Portal",
    "site_header": "ElimuHub",
    "site_brand": "ElimuHub ",
    
    # Colors matching your CSS variables
    "primary_color": "#dc2626",        # Your --primary-red
    "accent_color": "#3b82f6",         # Your --secondary-blue  
    "navbar_color": "#ffffff",
    "navbar_light_color": "#dc2626",
    "theme": "default",
    
    # Perfect sidebar settings for your CSS
    "sidebar_fixed": True,
    "navigation_expanded": True,       # Starts expanded (toggle works)
    "show_sidebar": True,
    "responsive": True,
    
    "site_logo": "img/logo.jpeg",     # Main sidebar logo
    "login_logo": "img/logo.jpeg",    # Login page logo  
    "site_icon": "img/favicon.ico", 
    
    # Rest of your original settings...
   
    
    "icons": {
        # ===== USER MANAGEMENT =====
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "school_app.User": "fas fa-user-tie",
        "school_app.UserSession": "fas fa-user-clock",
        "school_app.PasswordHistory": "fas fa-history",
        
        # ===== SECURITY =====
        "school_app.IPWhitelist": "fas fa-shield-alt",
        
        # ===== STUDENT MANAGEMENT =====
        "school_app.Student": "fas fa-user-graduate",
        "school_app.StudentAcademicHistory": "fas fa-history",
        "school_app.Parent": "fas fa-users",
        
        # ===== CBE ACADEMIC STRUCTURE =====
        "school_app.AcademicYear": "fas fa-calendar-alt",
        "school_app.Term": "fas fa-calendar-week",
        "school_app.LearningArea": "fas fa-graduation-cap",
        "school_app.Strand": "fas fa-project-diagram",
        "school_app.SubStrand": "fas fa-code-branch",
        "school_app.Competency": "fas fa-bullseye",
        
        # ===== SUMMATIVE ASSESSMENT (CBE) =====
        "school_app.AssessmentWindow": "fas fa-window-restore",
        "school_app.SummativeAssessment": "fas fa-clipboard-check",
        "school_app.SummativeRating": "fas fa-star-half-alt",
        "school_app.TermlySummary": "fas fa-chart-bar",
        "school_app.CBEReportCard": "fas fa-file-contract",
        
        # ===== ACADEMICS =====
        "school_app.Class": "fas fa-chalkboard-teacher",
        "school_app.ClassSubjectAllocation": "fas fa-tasks",
        "school_app.Timetable": "fas fa-calendar-day",
        
        # ===== E-LEARNING =====
        "school_app.Course": "fas fa-book-open",
        "school_app.CourseModule": "fas fa-folder-open",
        "school_app.LearningContent": "fas fa-file-alt",
        "school_app.StudentEnrollment": "fas fa-user-plus",
        "school_app.ContentProgress": "fas fa-spinner",
        "school_app.ELearningQuiz": "fas fa-question-circle",
        "school_app.QuizQuestion": "fas fa-question",
        "school_app.QuizAttempt": "fas fa-pen-square",
        "school_app.DiscussionForum": "fas fa-comments",
        "school_app.ForumPost": "fas fa-comment",
        
        # ===== FINANCE =====
        "school_app.FeeCategory": "fas fa-money-bill-wave",
        "school_app.FeeStructure": "fas fa-table",
        "school_app.StudentFeeInvoice": "fas fa-file-invoice-dollar",
        "school_app.InvoiceItem": "fas fa-list",
        "school_app.FeeTransaction": "fas fa-exchange-alt",
        "school_app.GeneralLedger": "fas fa-book",
        "school_app.StudentCredit": "fas fa-credit-card",
        
        # ===== ATTENDANCE & DISCIPLINE =====
        "school_app.AttendanceSession": "fas fa-calendar-check",
        "school_app.StudentAttendance": "fas fa-user-check",
        "school_app.DisciplineCategory": "fas fa-exclamation-triangle",
        "school_app.DisciplineIncident": "fas fa-gavel",
        "school_app.StudentDisciplinePoints": "fas fa-chart-line",
        
        # ===== HUMAN RESOURCES =====
        "school_app.Staff": "fas fa-user-tie",
        "school_app.StaffLeave": "fas fa-umbrella-beach",
        "school_app.LeaveBalance": "fas fa-balance-scale",
        
        # ===== PAYROLL =====
        "school_app.PayrollComponent": "fas fa-calculator",
        "school_app.StaffPayrollComponent": "fas fa-user-cog",
        "school_app.PayrollPeriod": "fas fa-calendar",
        "school_app.PayrollRecord": "fas fa-file-invoice",
        "school_app.StaffLoan": "fas fa-hand-holding-usd",
        "school_app.LoanRepayment": "fas fa-money-check-alt",
        
        # ===== LIBRARY =====
        "school_app.BookResource": "fas fa-book",
        
        # ===== SYSTEM & AUDIT =====
        "school_app.AuditLog": "fas fa-clipboard-list",
        "school_app.BackupHistory": "fas fa-database",
        "school_app.SystemSetting": "fas fa-cog",
        
        # ===== UTILITY =====
        "school_app.Holiday": "fas fa-calendar-times",
        "school_app.Notification": "fas fa-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "welcome_sign": "Enter your login credentials",
    "copyright": "ElimuHub © 2026",
    "changeform_format": "horizontal_tabs",
    
  
    # Menu ordering (optional - organizes your sidebar)
    "order_with_respect_to": [
        "auth",
        "school_app.Student",
        "school_app.Staff",
        "school_app.FeeCategory",
        "school_app.Course",
        "school_app.LearningArea",
        "school_app.BookResource",
        "school_app.AuditLog",
    ],
    
    # Language
    "language_chooser": False,
    
    # Search bar configuration
    "search_model": ["school_app.Student", "school_app.Staff", "auth.User"],
    
    # Custom icons for app groups
    "custom_icons": {
        "auth": "icon-group",
        "school_app": "icon-school",
    },
}

# Optional: Group models in sidebar
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}



# Static files for custom CSS/logo
# Static files
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / "static"]
# STATIC_ROOT = BASE_DIR / "staticfiles"

# Static files settings for Render
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

