# Generated by Django 6.0.1 on 2026-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_stream_alter_class_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbereportcard',
            name='competency_ratings',
            field=models.JSONField(default=dict),
        ),
    ]
