# Generated by Django 6.0.1 on 2026-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_cbereportcard_competency_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-event_time']},
        ),
        migrations.AlterModelOptions(
            name='cbereportcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CREATE', 'User Create'), ('USER_UPDATE', 'User Update'), ('USER_DELETE', 'User Delete'), ('STUDENT_CREATE', 'Student Create'), ('STUDENT_UPDATE', 'Student Update'), ('STUDENT_DELETE', 'Student Delete'), ('FEE_CREATE', 'Fee Create'), ('FEE_UPDATE', 'Fee Update'), ('FEE_DELETE', 'Fee Delete'), ('PAYMENT_RECEIVED', 'Payment Received'), ('EXAM_CREATE', 'Exam Create'), ('EXAM_UPDATE', 'Exam Update'), ('MARKS_ENTERED', 'Marks Entered'), ('MARKS_MODIFIED', 'Marks Modified'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('DISCIPLINE_INCIDENT', 'Discipline Incident'), ('SYSTEM_BACKUP', 'System Backup'), ('SYSTEM_RESTORE', 'System Restore'), ('CONFIG_CHANGE', 'Config Change'), ('CBE_RATING_ENTERED', 'CBE Rating Entered'), ('CBE_REPORT_GENERATED', 'CBE Report Generated'), ('BULK_STATUS_UPDATE', 'Bulk Status Update')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='school_app__model_n_827b55_idx'),
        ),
    ]
