# Generated by Django 6.0.1 on 2026-06-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_auditlog_options_alter_cbereportcard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='studentacademichistory',
            name='section',
        ),
    ]
