# Generated by Django 6.0.1 on 2026-06-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_remove_student_current_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=255, unique=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('SCHEMA', 'Schema Only'), ('DATA', 'Data Only')], max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_path', models.CharField(max_length=500)),
                ('verification_status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backup_name'], name='school_app__backup__f5782c_idx'), models.Index(fields=['created_at'], name='school_app__created_ce28a6_idx'), models.Index(fields=['backup_type'], name='school_app__backup__71fa83_idx')],
            },
        ),
    ]
