# Generated by Django 6.0.1 on 2026-06-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_assignmentquestion_studentanswer'),
    ]

    operations = [
    ]
