# Generated by Django 6.0.1 on 2026-06-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_add_assignment_questions_data'),
        ('school_app', '0013_add_assignment_questions_data'),
    ]

    operations = [
    ]
