# Generated by Django 6.0.1 on 2026-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectallocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
